import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

/**
 * The invariants the CI step claims to check. Before this file existed, the step
 * was named for a test suite that did not exist, which is precisely the kind of
 * claim this site is built to not make.
 */

const read = (dir: string) => {
  const base = new URL(`../src/content/${dir}/`, import.meta.url).pathname;
  return readdirSync(base).map((f) => ({ file: f, text: readFileSync(join(base, f), "utf8") }));
};

const field = (text: string, key: string) => text.match(new RegExp(`^${key}:\\s*(.+)$`, "m"))?.[1];

const projects = read("projects");
const roles = read("roles");

describe("projects", () => {
  it("has no duplicate order, so the sort is deterministic", () => {
    const orders = projects.map((p) => field(p.text, "order"));
    expect(new Set(orders).size).toBe(projects.length);
  });

  it("gives every project a figure the reader can scan", () => {
    for (const p of projects) {
      expect(p.text, `${p.file} is missing a figure`).toMatch(/^figure:/m);
    }
  });

  it("never claims a store listing in prose without a status line", () => {
    for (const p of projects) {
      if (/App Store/i.test(p.text)) {
        expect(p.text, `${p.file} mentions the App Store but states no status`).toMatch(
          /^status:/m,
        );
      }
    }
  });
});

describe("roles", () => {
  it("has no duplicate order", () => {
    const orders = roles.map((r) => field(r.text, "order"));
    expect(new Set(orders).size).toBe(roles.length);
  });

  it("keeps `current` and `end: Present` in agreement", () => {
    for (const r of roles) {
      const current = field(r.text, "current") === "true";
      const present = field(r.text, "end")?.replaceAll('"', "") === "Present";
      expect(current, `${r.file}: current and end disagree`).toBe(present);
    }
  });
});

describe("the open graph card", () => {
  it("still quotes the hero copy it was generated from", () => {
    // og.png is committed and generated by hand. If the copy moves and the card
    // does not, the card is a stale claim. This is the check that catches it.
    const site = readFileSync(new URL("../src/lib/site.ts", import.meta.url), "utf8");
    const og = readFileSync(new URL("../scripts/og.mjs", import.meta.url), "utf8");
    const role = site.match(/role:\s*"([^"]+)"/)?.[1];

    expect(role).toBeTruthy();
    // The card renders site.role directly, so the generator must still read it
    // from the source of truth rather than hold its own copy.
    expect(og).toContain("site.role");
    expect(og).not.toMatch(/Product engineer|Full-stack and AI engineer/);
  });
});
