import { generateAscii } from "./ascii";

export const portfolioConfig = {
  profile: {
    projectName: "ENGINEER_CLI",
    name: "Huy",
    title: "SOFTWARE ENGINEER",
    asciiTitle: generateAscii("Huy Tran"),
    location: "Amsterdam, NL (AWS-01)",
    yearsXp: "4+",
    projectsCount: "10+",
    currentStack: ["K8S", "DOCKER", "NODE", "TS", "REACT"],
    summary: "High-availability engineer specializing in distributed systems, cloud-native infrastructure, and performance-critical full-stack applications. Bridging the gap between complex DevOps workflows and elegant frontend experiences.",
  },
  navigation: [
    { label: "/home", path: "/" },
    { label: "/experience", path: "/experience" },
    { label: "/projects", path: "/projects" },
    { label: "/stack", path: "/stack" },
    { label: "/contact", path: "/contact" },
  ],
  quickActions: [
    { label: "./view_projects", path: "/projects" },
    { label: "./read_experience", path: "/experience" },
    { label: "./download_cv", path: "/cv" },
  ],
  experiences: [
    {
      title: "DevOps Engineer",
      company: "In The Zone",
      place: "Amsterdam, Netherlands (Hybrid)",
      description: "The life toolkit for bipolar, designed for those who live it, and for those who stand beside them through it.",
      date: "April 2026 - Present",
      active: true,
    },
    {
      title: "Full-stack Developer",
      company: "SevginWeb",
      place: "Deventer, Netherlands (Remote)",
      description: "Revamped the payment process using modern design and functionality, improving user satisfaction and increasing the conversion rate by ~15% in the first few months post-deployment. Optimize the CI/CD pipeline of the application for a reliable deployment. Delivered a comprehensive notification service by implementing frontend and backend components, streamlining user communication and system alerts.",
      date: "Jan 2023 - March 2026",
      active: false,
    },
    {
      title: "Full-stack Developer Intern",
      company: "Accenture",
      place: "Amsterdam, Netherlands",
      description: "Researched and engineered microservices using Golang, Python, and React, ensuring scalable and efficient system performance. Deployed microservices on GCP via Azure Pipeline, leveraging Docker and Kubernetes to enable seamless and reliable operations. Enhanced user experience by redesigning the dashboard, improving the logical flow and intuitive presentation of information.",
      date: "May 2022 - Nov 2022",
      active: false,
    },
    {
      title: "Part-time Full-stack Developer",
      company: "SevginWeb",
      place: "Deventer, Netherlands (Remote)",
      description: "Developed SEO-focused blogs using Next.js and headless WordPress, boosting the click-through rate to the main site by ~20% within four months. Implemented a Geo-detection feature with Cloudflare Workers, reducing the bounce rate and improving user engagement over time.",
      date: "Aug 2021 - Dec 2022",
      active: false,
    },
    {
      title: "Full-stack Developer Intern",
      company: "Code.rehab",
      place: "Enschede, Netherlands",
      description: "Developed Front-end using React and GraphQL. Created microservices with Nodejs using AWS serverless for an online magazine platform. Implemented CI/CD pipeline between Jira and AWS.",
      date: "Feb 2021 - Jul 2021",
      active: false,
    },
  ],
  education: [
    {
      title: "BSc Computer Science",
      school: "Saxion University of Applied Sciences",
      place: "Deventer, Netherlands",
      date: "2018 - 2022",
    }
  ],
  projects: [
    {
      title: "Lorenly",
      description: "Multi-tenant SaaS for salons: booking, client CRM, gift cards, and an inline-editable site per tenant. Next.js on Cloudflare Workers (OpenNext) with host-based tenant resolution, a shared Supabase/Postgres schema, one-click data import from 9 competing booking systems, and an Expo companion app with push notifications on the App Store.",
      link: "https://lorenly.com/?utm_source=portfolio",
      tags: ["Next.js", "TypeScript", "Cloudflare Workers", "Supabase", "PostgreSQL", "Expo", "React Native", "Docker", "Multi-tenant"],
    },
    {
      title: "Perron",
      description: "Location-gated chat for Dutch train stations: you can only join a platform's room while physically standing on it. Expo client on a Cloudflare Workers backend, live departures from open CC0 GTFS-RT feeds instead of a vendor API, native push, and a subscription verified through the App Store Server API.",
      link: "https://perron.tranmani.com/?utm_source=portfolio",
      tags: ["Expo", "React Native", "TypeScript", "Cloudflare Workers", "GTFS-RT", "Push Notifications", "IAP"],
    },
    {
      title: "FamMedley",
      description: "A high-end family care coordination and safety platform featuring a Go-powered API supporting a cross-platform Expo (React Native) application. Features an AI-driven Meal Planner (with Tinder-style swiping), real-time collaborative Whiteboard, WebSocket-driven shared shopping lists with live presence tracking, and high-fidelity location mapping. Engineered with a highly resilient, offline-first SQLite sync engine with automatic mutation queue optimizations, and a premium UI/UX following 'The Kinetic Hearth' design principles. Integrated with RevenueCat for subscription entitlement, built with TypeScript, and deployed via containerized CI/CD to GCP",
      link: "https://fammedley.com/?utm_source=portfolio",
      tags: ["Go", "Expo", "React Native", "TypeScript", "PostgreSQL", "SQLite", "WebSockets", "RevenueCat", "Google Cloud Platform", "Docker", "GitHub Actions"],
    },
    {
      title: "CI/CD Pipeline Project",
      description: "Designed and implemented a multi-cloud CI/CD pipeline using Azure DevOps to build, containerize, and deploy a production Next.js application with Docker to Google Cloud Artifact Registry and Kubernetes (GKE), with cloud resources provisioned using Terraform. \nProvisioned and operated infrastructure and self-hosted CI agents via Terraform, implementing secure service-account authentication, Docker cache and storage optimization, and automated cleanup to ensure reliable, scalable deployments. ",
      tags: ["Azure DevOps", "Terraform", "Docker", "GKE", "K8s"],
    },
    {
      title: "Portfolio Website v2",
      description: "I updated my portfolio website to update my skills and projects.",
      link: "https://tranmani.com/?utm_source=portfolio",
      tags: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    },
    {
      title: "Managed Public Cloud",
      description: "Managed a public cloud infrastructure using OpenStack, hosting approximately 10 WordPress websites and counting and a selfhosted n8n automation system. \nGained hands-on experience with Linux and cloud infrastructure-as-a-service, enhancing system management and troubleshooting skills. Ensured reliable performance and uptime for hosted services.",
      tags: ["OpenStack", "Linux", "n8n", "Wordpress", "Cloud"],
    },
    {
      title: "Beauty Art Pro",
      description: "WordPress website for a local business in Geneva, Switzerland. Ranked top 5 in local Google search results within months.",
      link: "https://beautyartpro.eu/?utm_source=portfolio",
      tags: ["Wordpress", "SEO"],
    },
    {
      title: "Portfolio Website v1",
      description: "I created this website to showcase my best work and make it easy for others to access my resume. It's an invaluable tool for networking and job searching, as it allows me to connect with potential employers and showcase my expertise. On my website, I've included a selection of my best work, along with a summary of my education and qualifications and contact information for those interested in connecting with me.",
      link: "https://portfolio-git-v1-huy-trans-projects-c23295af.vercel.app/",
      tags: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    },
    {
      title: "Casino Review Website",
      description: "I developed an SEO-optimized satellite blog using Next.js and MUI to maximize search rankings, traffic, and lead generation for the business. This project leveraged server-side rendering and premium UI components to deliver a high-performance, visually appealing user experience.",
      link: "https://review.tranmani.com/?utm_source=portfolio",
      tags: ["React", "Next.js", "MUI"],
    },
    {
      title: "Headless WP Blog",
      description: "Developed a layout in React leveraging the power of headless WordPress for content writers.",
      link: "https://test-blog.tranmani.com/?utm_source=portfolio",
      tags: ["React", "Wordpress", "Next.js"],
    },
  ],
  contact: {
    email: "minhhuy8137@gmail.com",
    subject: "collaboration_proposal",
    linkedIn: "https://www.linkedin.com/in/minh-huy-tran/",
    github: "https://github.com/tranmani",
  },
  stackData: [
    { name: "React", category: "FRONTEND_UI" },
    { name: "Next.js", category: "META_FRAMEWORK" },
    { name: "TypeScript", category: "TYPE_SYSTEM" },
    { name: "Node.js", category: "RUNTIME_ENV" },
    { name: "TailwindCSS", category: "STYLING_ENGINE" },
    { name: "AWS", category: "CLOUD_INFRA" },
    { name: "Kubernetes", category: "ORCHESTRATION" },
    { name: "Docker", category: "CONTAINERIZATION" },
    { name: "PostgreSQL", category: "DATA_STORAGE" },
    { name: "MUI", category: "COMPONENT_LIB" },
    { name: "Framer Motion", category: "ANIMATION_SDK" },
    { name: "MongoDB", category: "NOSQL_DB" },
    { name: "Redis", category: "CACHE_DB" },
    { name: "GraphQL", category: "API_QUERY_LANG" },
    { name: "REST", category: "API_ARCH" },
    { name: "Cloudflare Worker", category: "SERVERLESS" },
    { name: "Azure Pipeline", category: "CI/CD" },
    { name: "GitHub Actions", category: "CI/CD" }
  ]
};
